name: as_wallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  web3dart: ^2.5.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  hex: ^0.2.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  line_icons: ^2.0.1
  google_fonts: ^4.0.3
  mobile_scanner: ^3.0.0
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
